### ISSUE TITLE
BUG-NullPointerException

### ISSUE THREAD

**Issue by junge89221** [azhon/AppUpdate#111]
**Bug标题**
升级出现空异常

**AppUpdate参数设置**
 
 
![1](https://user-images.githubusercontent.com/12729702/145748494-11bad756-332a-4dc1-8fb0-e918fc4b3d7d.png)

**复现步骤**
1、app进入后弹出升级弹框，最小化点击其他app
2、返回app点击升级出现

**错误Logcat日志截图**
日志截图
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.SoftReference.get()' on a null object reference
        at com.azhon.appupdate.manager.DownloadManager.checkParams(DownloadManager.java:375)
        at com.azhon.appupdate.manager.DownloadManager.download(DownloadManager.java:323)
        at cn.caep.stic.pages.app.lunch.LunchPresenter$updatePop$2.invoke$lambda-1(LunchPresenter.kt:38)
        at cn.caep.stic.pages.app.lunch.LunchPresenter$updatePop$2.$r8$lambda$Rswp1s81s2hUR6rVqw81Dd95Jvc(Unknown Source:0)
        at cn.caep.stic.pages.app.lunch.LunchPresenter$updatePop$2$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7312)
        at android.view.View.performClickInternal(View.java:7286)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28242)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
**软件版本信息**
 - Android Studio：Android Studio Arctic Fox | 2020.3.1 Patch 2
 - AppUpdate：
 - 设备品牌：华为
 - 设备型号：mate30
 - 设备系统版本：Android 10

**额外有用的信息**
补充额外有用的信息

**Comment by junge89221** [comment]
如果不点击其他app，直接升级提示： java.net.UnknownHostException: Unable to resolve host "test-tisp-tisp-minio-test-1-v-1-39-57-9000.paastest.caep.cn": No address associated with hostname，下载链接：http://test-tisp-tisp-minio-test-1-v-1-39-57-9000.paastest.caep.cn:11140/tisp-cms/apk/c.apk
