### ISSUE TITLE
android8.0上报Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by kuojy** [azhon/AppUpdate#160]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**
  java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                                                    	at com.android.server.am.ActivityRecord.setRequestedOrientation(ActivityRecord.java:2374)
                                                                                                    	at com.android.server.am.HwActivityRecord.setRequestedOrientation(HwActivityRecord.java:129)
                                                                                                    	at com.android.server.am.ActivityManagerService.setRequestedOrientation(ActivityManagerService.java:5520)
                                                                                                    	at com.android.server.am.HwActivityManagerService.setRequestedOrientation(HwActivityManagerService.java:1843)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1101)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3286)
                                                                                                    	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:837)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:675)
2024-02-28 12:01:48.760   779-2524  iMonitor                pid-779                              E  FaultDetect: DUMPTOOL_PRINTF return.
2024-02-28 12:01:48.761  8939-8939  AndroidRuntime          com.zx.zxt                           E  FATAL EXCEPTION: main
                                                                                                    Process: com.zx.zxt, PID: 8939
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zx.zxt/com.azhon.appupdate.view.UpdateDialogActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
                                                                                                    	at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                                                    	at android.os.Looper.loop(Looper.java:166)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                                                                    Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1962)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1900)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5704)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.sangfor.sdk.sandbox.Sangfor_a.Sangfor_b$Sangfor_b.invoke(Proguard:10)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
                                                                                                    	at $Proxy9.setRequestedOrientation(Unknown Source)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.sangfor.sdk.sandbox.Sangfor_a.Sangfor_b$Sangfor_b.invoke(Proguard:10)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
                                                                                                    	at $Proxy12.setRequestedOrientation(Unknown Source)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.sangfor.sdk.sandbox.Sangfor_a.Sangfor_b$Sangfor_b.invoke(Proguard:10)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
                                                                                                    	at $Proxy12.setRequestedOrientation(Unknown Source)
                                                                                                    	at android.app.Activity.setRequestedOrientation(Activity.java:6132)
                                                                                                    	at com.jxaic.wsdj.base.App.onActivityCreated(App.java:609)
                                                                                                    	at android.app.Application.dispatchActivityCreated(Application.java:208)
                                                                                                    	at android.app.Activity.onCreate(Activity.java:1110)
                                                                                                    	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:314)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                                                                                                    	at com.azhon.appupdate.view.UpdateDialogActivity.onCreate(UpdateDialogActivity.kt:55)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7383)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.sangfor.sdk.sandbox.Sangfor_a.Sangfor_b$Sangfor_b.invoke(Proguard:10)
                                                                                                    	at android.app.Instrumentation_Proxy.callActivityOnCreate(Unknown Source:20)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) 
                                                                                                    	at android.app.ActivityThread.-wrap12(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                                                                    	at android.os.Looper.loop(Looper.java:166) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7529) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
**Software version**
 - Android Studio：Android Studio Giraffe | 2022.3.1 Patch3
 - AppUpdate Version：4.2.8
 - Device Brand：华为P9
 - Device Model：android
 - Android Version：android8.0

**Comment by azhon** [comment]
AppUpdate版本是多少？

**Comment by kuojy** [comment]
4.2.8，反馈里有写。

Android Studio：Android Studio Giraffe | 2022.3.1 Patch3

AppUpdate Version：4.2.8

Device Brand：华为P9

Device Model：android

Android Version：android8.0

&nbsp;


Kuo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Code ***@***.***&gt;; 
发送时间: 2024年2月28日(星期三) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [azhon/AppUpdate] android8.0上报Only fullscreen activities can request orientation (Issue #160)





 
AppUpdate版本是多少？

**Comment by azhon** [comment]
代码里没有请求orientation呀，你试试demo看会不会报错？

**Comment by kuojy** [comment]
demo没问题，刚排查下，app启动时，是自己在项目里的application里调用了setRequestedOrientation，然后打开updateDialgoActivity就会报错，不调app升级框架就没事。现在屏蔽掉application里的
setRequestedOrientation就好了

Kuo
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azhon/AppUpdate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azhon/AppUpdate] android8.0上报Only fullscreen activities can request orientation (Issue #160)





 
代码里没有请求orientation呀，你试试demo看会不会报错？
