### ISSUE TITLE
测试发现在华为荣耀6 PLUS上点击更新出现闪退。

### ISSUE THREAD

**Issue by coderZy2015** [azhon/AppUpdate#18]
机型是几年前的，Android6.0, 其他的手机发起申请权限暂无发现。
错误信息：
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:757)
	at android.app.ContextImpl.startActivity(ContextImpl.java:737)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
	at com.azhon.appupdate.manager.DownloadManager.download(DownloadManager.java:220)
	at com.gl.education.home.fragment.HomePageFragment$3.onClick(HomePageFragment.java:295)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by coderZy2015** [comment]
嗯，没问题了
