### ISSUE TITLE
解析包出错

### ISSUE THREAD

**Issue by yushilong** [azhon/AppUpdate#37]
2019-05-22 14:37:53.491 31851-32114/com.yao W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.azhon.appupdate.manager.HttpDownloadManager.getContentLength(HttpDownloadManager.java:228)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.azhon.appupdate.manager.HttpDownloadManager.breakpointDownload(HttpDownloadManager.java:94)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.azhon.appupdate.manager.HttpDownloadManager.access$300(HttpDownloadManager.java:36)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at com.azhon.appupdate.manager.HttpDownloadManager$2.run(HttpDownloadManager.java:82)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-05-22 14:37:53.492 31851-32114/com.yao W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err: 	... 20 more
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-05-22 14:37:53.493 31851-32114/com.yao W/System.err: 	... 33 more

**Comment by yushilong** [comment]
证书问题
