### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by liking158** [azhon/AppUpdate#41]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.azhon.appupdate.config.UpdateConfiguration.isEnableLog()' on a null object reference
        at com.azhon.appupdate.utils.LogUtil.<clinit>(LogUtil.java:26)
        at com.azhon.appupdate.utils.LogUtil.e(LogUtil.java:36) 
        at com.azhon.appupdate.manager.DownloadManager.checkParams(DownloadManager.java:348) 
        at com.azhon.appupdate.manager.DownloadManager.download(DownloadManager.java:291)

**Comment by azhon** [comment]
你是怎么使用的？
你直接使用的LogUtil?

**Comment by liking158** [comment]
没有使用，我直接implementation 'com.azhon:appupdate:2.1.0'
然后调用
      DownloadManager  manager = DownloadManager.getInstance(UploadActivity.this);
        manager.setApkName(context.getString(R.string.app_name))
                .setApkUrl(url)
                .setDownloadPath(Environment.getExternalStorageDirectory() + "/AppUpdate")
                .setSmallIcon(R.mipmap.ic_launcher)
                .download();
就出现的，是不是因为我也有个这个工具类LogUtil，两个冲突导致的？

**Comment by azhon** [comment]
不像，你试下安装demo看下------------------ 原始邮件 ------------------
发件人: "liking158"<notifications@github.com>
发送时间: 2019年6月27日(星期四) 下午5:20
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>;
抄送: "Code Porter"<958460248@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [azhon/AppUpdate] 发现一个bug (#41)



没有使用，我直接implementation 'com.azhon:appupdate:2.1.0'
 然后调用
 DownloadManager  manager = DownloadManager.getInstance(UploadActivity.this);
 manager.setApkName(context.getString(R.string.app_name))
 .setApkUrl(url)
 .setDownloadPath(Environment.getExternalStorageDirectory() + "/AppUpdate")
 .setSmallIcon(R.mipmap.ic_launcher)
 .download();
 就出现的，是不是因为我也有个这个工具类LogUtil，两个冲突导致的？
 
&mdash;

**Comment by liking158** [comment]
好的，我再试试

**Comment by liking158** [comment]
不好意思，我的方法使用不当造成的，这个报错我自己关了啊
