### ISSUE TITLE
 .setBreakpointDownload(false) 的情况下，(len = is.read(buffer) 超时 （仅在华为设备出现）

### ISSUE THREAD

**Issue by BergenWang** [azhon/AppUpdate#49]
设置.setBreakpointDownload(false)
使用华为mate20 Android9.0测试，07-31 17:19:18.847 20724-21548/com.azhon.app W/System.err: java.net.SocketTimeoutException: timeout  (试过好几款华为手机都是这样,比如honor 8 Android 8.0)

又试过努比亚，三星，小米，oppo等其他手机 没有该问题，另，修改超时时间为30s+也没用，一样会超时。
全部错误日志如下：
07-31 17:19:18.847 20724-21548/com.azhon.app W/System.err: java.net.SocketTimeoutException: timeout
07-31 17:19:18.848 20724-21548/com.azhon.app W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
07-31 17:19:18.849 20724-21548/com.azhon.app W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
        at java.io.InputStream.read(InputStream.java:101)
        at com.azhon.appupdate.manager.HttpDownloadManager.fullDownload(HttpDownloadManager.java:187)
07-31 17:19:18.850 20724-21548/com.azhon.app W/System.err:     at com.azhon.appupdate.manager.HttpDownloadManager.access$500(HttpDownloadManager.java:36)
        at com.azhon.appupdate.manager.HttpDownloadManager$2.run(HttpDownloadManager.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
07-31 17:19:18.851 20724-21548/com.azhon.app W/System.err: Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    	... 10 more

**Comment by azhon** [comment]
这就奇葩了，你拿华为试试其它下载地址看看

**Comment by BergenWang** [comment]
> 
> 
> 这就奇葩了，你拿华为试试其它下载地址看看

我换成QQ的下载地址，可以正常下载；那么判断下载的地址有问题！然后我又还原成原来的下载地址（我们公司自己的产品），然后换成4g下载居然可以成功！
也就是说上诉的bug必须是在我们公司内部的wifi下载我们自己线上的apk包，并且是华为手机才会出现（如果是我们公司内部网络有什么问题，为什么仅仅华为有问题，我试过很多机型，只有华为有问题）。。。。我也懵逼了.

**Comment by azhon** [comment]
那我也无能为力了，估计是你们网络的问题
