### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by c4jeff** [azhon/AppUpdate#53]
D/AppUpdate.DownloadService: 应用的通知栏开关状态：已打开
E/AppUpdate.DownloadService: error: java.lang.ArrayIndexOutOfBoundsException: src.length=2048 srcPos=0 dst.length=65536 dstPos=37342 length=-37342
 ```java
java.lang.ArrayIndexOutOfBoundsException: src.length=2048 srcPos=0 dst.length=65536 dstPos=37342 length=-37342
     at java.lang.System.arraycopy(Native Method)
     at com.azhon.appupdate.io.BufferedRandomAccessFile.writeAtMost(BufferedRandomAccessFile.java:347)
     at com.azhon.appupdate.io.BufferedRandomAccessFile.write(BufferedRandomAccessFile.java:319)
     at com.azhon.appupdate.manager.HttpDownloadManager.breakpointDownload(HttpDownloadManager.java:132)
     at com.azhon.appupdate.manager.HttpDownloadManager.access$400(HttpDownloadManager.java:36)
     at com.azhon.appupdate.manager.HttpDownloadManager$2.run(HttpDownloadManager.java:83)
     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:784)

**Comment by azhon** [comment]
我这边查看下
