### ISSUE TITLE
red mi 4 经常报java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by JhoBor** [azhon/AppUpdate#65]
java.net.SocketTimeoutException: timeout
    at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
    at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
    at java.io.InputStream.read(InputStream.java:101)
    at com.azhon.appupdate.manager.HttpDownloadManager.fullDownload(HttpDownloadManager.java:98)
    at com.azhon.appupdate.manager.HttpDownloadManager.access$200(HttpDownloadManager.java:33)
    at com.azhon.appupdate.manager.HttpDownloadManager$2.run(HttpDownloadManager.java:73)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:144)
    at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 10 more

**Comment by azhon** [comment]
其他手机用同样的网络会报吗？

**Comment by JhoBor** [comment]
更正一下，是红米note 7，不是红米4。其它手机不会，就红米note 7 偶尔能下载完成，但大多数情况是下载到百分之十几到二十几就报超时异常了

在 2019-11-07 20:46:44，"Code Porter" <notifications@github.com> 写道：


其他手机用同样的网络会报吗？

**Comment by azhon** [comment]
后面版本中优化一下下载
