### ISSUE TITLE
下载过程中创建Notifycation出错

### ISSUE THREAD

**Issue by niebiao** [azhon/AppUpdate#82]
2020-03-26 20:16:05.610 4594-4594/com.ky.em D/AppUpdate.DownloadService: 应用的通知栏开关状态：已打开
2020-03-26 20:16:05.610 4594-4594/com.ky.em D/AppUpdate.DownloadService: 文件不存在开始下载
2020-03-26 20:16:05.615 4594-4807/com.ky.em E/AndroidRuntime: FATAL EXCEPTION: app update thread
    Process: com.ky.em, PID: 4594
    java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.ky.em-6DpFQhhJDJGVzn8d54W68g==/split_lib_dependencies_apk.apk)
        at com.azhon.appupdate.utils.NotificationUtil.builderNotification(NotificationUtil.java:49)
        at com.azhon.appupdate.utils.NotificationUtil.showNotification(NotificationUtil.java:73)
        at com.azhon.appupdate.service.DownloadService.start(DownloadService.java:135)
        at com.azhon.appupdate.manager.HttpDownloadManager.fullDownload(HttpDownloadManager.java:81)
        at com.azhon.appupdate.manager.HttpDownloadManager.access$200(HttpDownloadManager.java:33)
        at com.azhon.appupdate.manager.HttpDownloadManager$2.run(HttpDownloadManager.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by azhon** [comment]
你依赖的support v4包有问题，和demo对比一下
