### ISSUE TITLE
android 10运行闪退

### ISSUE THREAD

**Issue by jet6666** [azhon/AppUpdate#97]
虚拟机：
anddroid 10.0+ (Google APIs)

直接闪退
`2020-08-27 18:39:52.034 11981-11981/com.azhon.app D/AndroidRuntime: Shutting down VM 

2020-08-27 18:39:52.035 11981-11981/com.azhon.app E/AndroidRuntime: FATAL EXCEPTION: main
 
    Process: com.azhon.app, PID: 11981
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at com.azhon.appupdate.manager.DownloadManager.checkParams(DownloadManager.java:376)
        at com.azhon.appupdate.manager.DownloadManager.download(DownloadManager.java:323)
        at com.azhon.app.MainActivity.startUpdate3(MainActivity.java:149)
        at com.azhon.app.MainActivity.onClick(MainActivity.java:69)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by azhon** [comment]
晚点我试试

**Comment by azhon** [comment]
我这边测试了下是没有问题。后面版本在这价格判null看看
